services:
  - type: web
    name: smavesto-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smavestodb
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: smavestodb
    engine: postgres
    plan: free
